name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install dependencies
        env:
          GOPROXY: https://proxy.golang.org,direct
        run: go mod download
      - name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
  build-wasm:
    name: Build WASM
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Build WASM
        run: GOOS=js GOARCH=wasm go build -o shiftcomply.wasm ./cmd/wasm
      - name: Check WASM size
        run: ls -lh shiftcomply.wasm
